FROM node:18-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=5000

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

# Установка nodemon для hot-reload
RUN npm install -g nodemon

EXPOSE ${PORT}

CMD ["nodemon", "--inspect=0.0.0.0:9229", "--exec", "npm", "run", "dev"]
