version: '3.8'

services:
  app:
    build: .
    image: processing-platform:prod
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    env_file: .env.prod

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongodb_data:
  redis_data:
