version: '3.8'

services:
  backend:
    build: ../backend
    context: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DEBUG=${DEBUG:-0}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
